server:
  port: 8988
  servlet:
    context-path: /api

spring:
  datasource:
    # mysql 数据库配置
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://192.168.1.2:3306/admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
   username: root
   password: root
    # h2 数据库配置
    # url: jdbc:h2:${engine.h2_path};MODE=MySQL;AUTO_RECONNECT=TRUE;INIT=RUNSCRIPT FROM 'sql/h2.sql'
    # username: root
    # password: root
    # driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never

mybatis-plus:
  global-config:
    banner: false
    enable-sql-runner: true
  configuration:
    # 开启驼峰转下划线
    map-underscore-to-camel-case: true

# 引擎配置
engine:
  # 存储版本库目录（存储库的文件都会存储到这个位置，比如库文件等）
  version_path: '/tmp/rece'
  # 缓存文件目录
  cache_path: '/tmp/Receptionist/cache/'
  # H2 数据库存储位置
  h2_path: '/tmp/Receptionist/h2/receptionist.db'

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  is-read-header: true

# SpringDoc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.tineaine.receptionistservice